### ISSUE TITLE
Does it use double opt-in?

### ISSUE THREAD

**Issue by phpSoftware** [michalbiarda/grav-plugin-newsletter#1]

**Comment by michalbiarda** [comment]
@phpSoftware No, it does not. It's a very simple plugin that allows to collect subscribers with a simple form, and stores data in CSV format. It also allow to unsubscribe. And that's it. I'm not maintaining it for years BTW.

**Comment by phpSoftware** [comment]
Too bad, but thanks for the quick reply and best regards to Poland
